name: manual-bazel-ci

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ["self-hosted", "linux"]
    
    steps:
    - name: Check Runner Architecture
      run: |
        echo "Runner Architecture: ${{ runner.os }} ${{ runner.arch }}"

    - name: Set Bazelisk version
      run: |
        echo "BAZELISK=v1.1.0" >> ${GITHUB_ENV}
        echo "ARCH=$(echo ${{ runner.arch }} | tr '[:upper:]' '[:lower:]')" >> ${GITHUB_ENV}

    - uses: actions/checkout@v2

    - name: Mount bazel cache
      uses: actions/cache@v1
      with:
        path: "/home/runner/.cache/bazel"
        key: bazel

    - name: Install bazelisk
      run: |
        curl -LO "https://github.com/bazelbuild/bazelisk/releases/download/${BAZELISK}/bazelisk-linux-${ARCH}"
        mkdir -p "${GITHUB_WORKSPACE}/bin/"
        mv "bazelisk-linux-${ARCH}" "${GITHUB_WORKSPACE}/bin/bazel"
        chmod +x "${GITHUB_WORKSPACE}/bin/bazel"
        ls -alh ${GITHUB_WORKSPACE}/bin/bazel
    - name: Test
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" test //...

    - name: Build
      run: |
        "${GITHUB_WORKSPACE}/bin/bazel" build //...